server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor #队列名称
    routingkey-media-video: routingkey_media_video #routingKey
  #视屏存放的目录
  video-location: F:\WebStorm\static\video\
  #ffmpeg处理视屏插件的地址
  ffmpeg-path: F:\FFmpeg\bin\ffmpeg.exe